oc_louvre_homepage:
    path:     /
    defaults:
        _controller: OCLouvreBundle:Booking:booking

oc_louvre_summary:
    path:     /summary/{btoken}
    defaults:
        _controller: OCLouvreBundle:Summary:summary

oc_louvre_payment:
    path:     /payment/{btoken}
    defaults:
        _controller: OCLouvreBundle:Payment:payment

oc_louvre_currentorder:
    path:     /ajax
    defaults:
        _controller: OCLouvreBundle:CurrentOrder:getorder
    methods: [post]

